---
kind: pipeline
name: default

steps:
  - name: firstphase
    image: alpine:3.8
    commands:
      - date -u -Iseconds
      - echo 'Hello world'
      - pwd
      - date > currentTime
      - find .
      - printenv
      - date -u -Iseconds

  - name: secondphase
    image: alpine:3.8
    commands:
      - date -u -Iseconds
      - echo 'Hello world'
      - pwd
      - cat currentTime
      - find .
      - echo ">.<"
      - date -u -Iseconds
