---
kind: pipeline
name: default

steps:
- name: firstphase
  image: alpine:3.8
  commands:
  - echo 'Hello world'
  - pwd
  - date > currentTime
  - find .
  - printenv

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock
