pipeline:
  firstphase:
    image: alpine:3.8
    commands:
    - echo 'Hello world'
    - pwd
    - date > currentTime
    - find .
    - printenv
  docker_image:
    image: plugins/docker
    repo: testing/container
    tags:
    - latest
    - "${CI_COMMIT_SHA}"
    dockerfile: Dockerfile
    save:
      destination: "testing-${CI_COMMIT_SHA}.tar"
  secondphase:
    image: alpine:3.8
    commands:
    - echo 'Hello world'
    - pwd
    - cat currentTime
    - find .
    - printenv
